
export const foodApi: foodItemType[] = [
    {
        id: "1",
        category: "Biryani",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/dlkugxln3bpvr3jouumx",
        title: "Rayyan Biryani",
        description: "Biryani, Mughlai",
        price: 120,
        originalPrice: 240,
        rating: 3.5,
        deliveryTime: "25-30 mins",
    },
    {
        id: "2",
        category: "Pizza",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/d20fdc8c86aa8bd0638f47dd013d46f9",
        title: "La Pino'z Pizza",
        description: "Pizzas, Pastas, Italian, Desserts, Beverages",
        price: 100,
        originalPrice: 150,
        rating: 4.2,
        deliveryTime: "30-35 mins",
    },
    {
        id: "3",
        category: "Burger",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e33e1d3ba7d6b2bb0d45e1001b731fcf",
        title: "Burger King",
        description: "Burgers, American",
        price: 150,
        originalPrice: 200,
        rating: 4.3,
        deliveryTime: "30-35 mins",
    },
    {
        id: "4",
        category: "Chicken",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/bedbbaa7543c3d70d7a01b02046ee86e",
        title: "Haji Saheb Park Circus",
        description: "Mughlai, North Indian, Chinese",
        price: 180,
        originalPrice: 250,
        rating: 4.4,
        deliveryTime: "30-35 mins",
    },
    {
        id: "5",
        category: "Others",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/g19qcakoqpbtcotb9viv",
        title: "The Hot Kati Roll",
        description: "Indian",
        price: 100,
        originalPrice: 120,
        rating: 4.1,
        deliveryTime: "30-35 mins",
    },
    {
        id: "6",
        category: "Biryani",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/4a25600fed5ae7a75ee70a91e0a885cd",
        title: "ELAHI LUXURY DINING",
        description: "North Indian, Chinese, Biryani, Kebabs, Seafood, Desserts, Beverages",
        price: 150,
        originalPrice: 200,
        rating: 4.5,
        deliveryTime: "35-40 mins",
    },
    {
        id: "7",
        category: "Biryani",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2b579171cefc545ce6479e21c0016798",
        title: "Veg Daawat by Behrouz",
        description: "Biryani, North Indian, Kebabs, Mughlai, Beverages, Desserts",
        price: 199,
        originalPrice: 299,
        rating: 4.4,
        deliveryTime: "35-40 mins",
    },
    {
        id: "8",
        category: "Others",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/63178e3e64d503a479f2a2048a474552",
        title: "Subway",
        description: "Healthy Food, Salads, Snacks, Desserts, Beverages",
        price: 120,
        originalPrice: 200,
        rating: 4.3,
        deliveryTime: "15-20 mins",
    },
    {
        id: "9",
        category: "Others",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/77d2fffe27cd59af5045a102d08af522",
        title: "Tea Junction",
        description: "Beverages, Snacks, Desserts",
        price: 100,
        originalPrice: 150,
        rating: 4.2,
        deliveryTime: "20-25 mins",
    },
    {
        id: "10",
        category: "Biryani",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/06f5c10f23e56a63ce7f6661433eaaa4",
        title: "Shawarma Nation",
        description: "Rolls & Wraps, Biryani, Snacks, Mexican, Lebanese, Salads, Healthy Food",
        price: 150,
        originalPrice: 220,
        rating: 4.5,
        deliveryTime: "30-35 mins",
    },
    {
        id: "11",
        category: "Others",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/vmfwltcmmknymzyxdylw",
        title: "Zafrani's",
        description: "Indian, Chinese",
        price: 120,
        originalPrice: 180,
        rating: 4.8,
        deliveryTime: "20-30 mins",
    },
    {
        id: "12",
        category: "Burger",
        imgSrc: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/m0pk8zgq3l4upgqdtfjn",
        title: "Taste Of King",
        description: "Continental, Burgers, Snacks, Beverages",
        price: 125,
        originalPrice: 210,
        rating: 4.2,
        deliveryTime: "30-35 mins",
    },
]

